package com.harshit.bean;
// Generated 1 Aug, 2023 11:01:19 PM by Hibernate Tools 4.3.1



/**
 * Emp generated by hbm2java
 */
public class Emp  implements java.io.Serializable {


     private int empno;
     private String name;
     private Float sal;
     private Integer deptno;
     private String gender;
     private Float comm;

    public Emp() {
    }

	
    public Emp(int empno) {
        this.empno = empno;
    }
    public Emp(int empno, String name, Float sal, Integer deptno, String gender, Float comm) {
       this.empno = empno;
       this.name = name;
       this.sal = sal;
       this.deptno = deptno;
       this.gender = gender;
       this.comm = comm;
    }
   
    public int getEmpno() {
        return this.empno;
    }
    
    public void setEmpno(int empno) {
        this.empno = empno;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Float getSal() {
        return this.sal;
    }
    
    public void setSal(Float sal) {
        this.sal = sal;
    }
    public Integer getDeptno() {
        return this.deptno;
    }
    
    public void setDeptno(Integer deptno) {
        this.deptno = deptno;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public Float getComm() {
        return this.comm;
    }
    
    public void setComm(Float comm) {
        this.comm = comm;
    }




}


